enum types {
  LOGIN = "user/LOGIN",
  LOGIN_SUCCESS = "user/LOGIN/SUCCESS",
  LOGIN_FAILED = "user/LOGIN/FAILED",
  AUTHORIZE = "user/AUTHORIZE",
  AUTHORIZE_SUCCESS = "user/AUTHORIZE/SUCCESS",
  AUTHORIZE_FAILED = "user/AUTHORIZE/FAILED",
  LOGOUT = "user/LOGOUT",
  LOGOUT_SUCCESS = "user/LOGOUT/SUCCESS"
}

export default types;
